// @flow
import { fromPairs } from 'lodash';
import {
  DuoSynthNode,
  SynthNode,
  AttackReleaseNode,
  AudioMasterNode,
  PannerNode,
  FeedbackDelayNode,
  AudioDelayNode,
  AudioGainNode,
  SetNoteNode,
  TimeLoopNode,
  StartTransportNode,
  TransportTimeNode,
  ConnectNode,
  ContextDestinationNode,
  ToContextDestinationNode,
  PianoNode,
  ArpeggiateNode,
  CompressorNode,
  ReverbNode,
  PlayerNode,
  VolumeNode,
  SignalRampNode,
  NoiseNode,
} from './ToneNode';
import { SoundFontNode, SoundFontPlayerNode } from './SoundFont';
import MapperNode from './MapperNode';
import IntervalNode from './IntervalNode';
import ThreeNode, {
  Color,
  DirectionalLightNode,
  AmbientLightNode,
  GlitchPassNode,
  ScanlinePassNode,
  DotScreenPassNode,
  VignettePassNode,
  NoisePassNode,
} from './ThreeNode';
import {
  TorusKnotGeometryNode,
  PlaneGeometryNode,
  SphereGeometryNode,
  BoxGeometryNode,
  GeometryBase,
} from './Geometries';
import {
  LambertMaterialNode,
  ShaderMaterialNode,
  ParticleMaterialNode,
  LoadTextureNode,
} from './MaterialNode';
import { AndNode, OrNode, NotNode, EqualsNode, SwitchNode } from './Logic';
import MeshNode, { PointsNode, LineNode } from './MeshNode';
import { MidiOutNode, MidiInNode } from './Midi';
import {
  InfoLog,
  JSONParse,
  ExtractNode,
  SetNode,
  StephenWolfram,
  CollectNode,
  JoinNode,
  RegexReplace,
  ArrayFillNode,
  CountSourceNode,
  ZipNode,
  NullNode,
} from './UtilNodes';
import Vector2D from './Vector2D';
import Vector3D from './Vector3D';
import { DomNode } from './Dom';
import { PlusNode } from './String';
import { ScaleNode, ChromaNode, ChordNode, TransposeNode, KeyTriadsNode } from './Music';
import { PerformanceRNNNode, LSTMCellNode, MultiRNNCellNode } from './Neural';
import { DivideNode, SumNode, ProductNode, IntToIntMathNode } from './MathNodes';
import { GPGPUProgramNode, RunGPGPUProgramNode } from './GPGPU';
import { JSCodeNode } from './Code';
import { number, string, boolean, date } from './primitives';

/**
 * Aggregator file to export all the nodes from a single place.
 * Eventually this should be separated to packages (maybe)
 *
 * Eventually this should be code-gen'd.
 */
export {
  Vector2D,
  MeshNode,
  PointsNode,
  LineNode,
  TorusKnotGeometryNode,
  LambertMaterialNode,
  ShaderMaterialNode,
  ParticleMaterialNode,
  LoadTextureNode,
  BoxGeometryNode,
  GeometryBase,
  ThreeNode,
  DuoSynthNode,
  SynthNode,
  AttackReleaseNode,
  AudioMasterNode,
  PannerNode,
  FeedbackDelayNode,
  AudioDelayNode,
  AudioGainNode,
  MapperNode,
  IntervalNode,
  SetNoteNode,
  TimeLoopNode,
  StartTransportNode,
  TransportTimeNode,
  ConnectNode,
  ContextDestinationNode,
  ToContextDestinationNode,
  PianoNode,
  ArpeggiateNode,
  CompressorNode,
  ReverbNode,
  PlayerNode,
  VolumeNode,
  SignalRampNode,
  NoiseNode,
  SoundFontNode,
  SoundFontPlayerNode,
  DivideNode,
  SumNode,
  ProductNode,
  IntToIntMathNode,
  Color,
  DirectionalLightNode,
  AmbientLightNode,
  GlitchPassNode,
  ScanlinePassNode,
  DotScreenPassNode,
  VignettePassNode,
  NoisePassNode,
  Vector3D,
  AndNode,
  OrNode,
  NotNode,
  EqualsNode,
  SwitchNode,
  PerformanceRNNNode,
  MultiRNNCellNode,
  LSTMCellNode,
  InfoLog,
  ScaleNode,
  ChromaNode,
  ChordNode,
  TransposeNode,
  KeyTriadsNode,
  MidiOutNode,
  MidiInNode,
  JSONParse,
  ExtractNode,
  SetNode,
  StephenWolfram,
  CollectNode,
  JoinNode,
  RegexReplace,
  ArrayFillNode,
  CountSourceNode,
  ZipNode,
  NullNode,
  DomNode,
  PlusNode,
  GPGPUProgramNode,
  RunGPGPUProgramNode,
  JSCodeNode,
  number,
  string,
  boolean,
  date,
};

export const allNodes = [
  Vector2D,
  MeshNode,
  PointsNode,
  LineNode,
  TorusKnotGeometryNode,
  PlaneGeometryNode,
  SphereGeometryNode,
  BoxGeometryNode,
  GeometryBase,
  LambertMaterialNode,
  ShaderMaterialNode,
  ParticleMaterialNode,
  LoadTextureNode,
  ThreeNode,
  DuoSynthNode,
  SynthNode,
  AttackReleaseNode,
  AudioMasterNode,
  PannerNode,
  FeedbackDelayNode,
  AudioDelayNode,
  AudioGainNode,
  MapperNode,
  IntervalNode,
  SetNoteNode,
  TimeLoopNode,
  StartTransportNode,
  TransportTimeNode,
  ConnectNode,
  ContextDestinationNode,
  ToContextDestinationNode,
  PianoNode,
  ArpeggiateNode,
  CompressorNode,
  ReverbNode,
  PlayerNode,
  VolumeNode,
  SignalRampNode,
  NoiseNode,
  SoundFontNode,
  SoundFontPlayerNode,
  DivideNode,
  SumNode,
  ProductNode,
  IntToIntMathNode,
  Color,
  DirectionalLightNode,
  AmbientLightNode,
  GlitchPassNode,
  ScanlinePassNode,
  DotScreenPassNode,
  VignettePassNode,
  NoisePassNode,
  Vector3D,
  AndNode,
  OrNode,
  NotNode,
  EqualsNode,
  SwitchNode,
  PerformanceRNNNode,
  MultiRNNCellNode,
  LSTMCellNode,
  InfoLog,
  ScaleNode,
  ChromaNode,
  ChordNode,
  TransposeNode,
  KeyTriadsNode,
  MidiOutNode,
  MidiInNode,
  JSONParse,
  ExtractNode,
  SetNode,
  StephenWolfram,
  CollectNode,
  JoinNode,
  RegexReplace,
  ArrayFillNode,
  CountSourceNode,
  ZipNode,
  NullNode,
  DomNode,
  PlusNode,
  GPGPUProgramNode,
  RunGPGPUProgramNode,
  JSCodeNode,
  number,
  string,
  boolean,
  date,
];

window.allNodes = allNodes;

const NodeRegistry = fromPairs(allNodes.map(n => [n.getRegistryName(), n]));
if (Object.keys(NodeRegistry).length !== allNodes.length) {
  throw new Error('duplicate node by registryName in node registry');
}
window.NodeRegistry = NodeRegistry;
